// /app/api/chat/_lib/memory/heuristic.ts
import type { Lang } from "../text";
import type { MemoryItem } from "../db/memoriesFilters";

/**
 * Deterministic heuristic extractor for durable memories.
 *
 * Source-of-truth policy:
 * - Prefer confirmed memory candidates generated by HOPY when available.
 * - This fallback reads the user's own durable wording.
 * - Memories are only one destination of HOPY-confirmed meaning.
 *
 * Goal:
 * - capture ONLY user-specific, durable memories
 * - never save chat logs verbatim
 * - keep extraction conservative for beta stability
 *
 * Hard exclusions (never store):
 * - Generic output format/style rules
 * - Temporary chat operation notes
 * - Generic self-help / non-user-specific statements
 * - Product/system architecture / HOPY dev definitions
 * - One-off feelings / transient facts / temporary tasks
 *
 * Durable inclusions:
 * - User's long-term preferences
 * - User's recurring dislikes / hard constraints
 * - User's HOPY support preferences
 * - User's HOPY development support preferences
 *
 * Constraints:
 * - 0..3 items
 * - content <= 120 chars (trimmed)
 * - importance: 3 (preference) / 4 (rule) / 5 (hard constraint)
 */

type HeuristicMemoryType = "trait" | "theme";

type HeuristicMemoryItem = MemoryItem & {
  memory_type: HeuristicMemoryType;
  source_type: "auto";
  save_hint: "save";
};

function trimTo(s: string, max = 120) {
  const t = String(s ?? "").replace(/\s+/g, " ").trim();
  if (!t) return "";
  return t.length <= max ? t : t.slice(0, max).trimEnd();
}

function splitSentencesJa(s: string): string[] {
  return String(s ?? "")
    .split(/[\n。！？!?]+/)
    .map((x) => x.trim())
    .filter(Boolean);
}

function splitSentencesEn(s: string): string[] {
  return String(s ?? "")
    .split(/[\n.!?]+/)
    .map((x) => x.trim())
    .filter(Boolean);
}

function uniqPush(out: HeuristicMemoryItem[], item: HeuristicMemoryItem) {
  const key = item.content;
  if (!key) return;
  if (out.some((x) => x.content === key)) return;
  out.push(item);
}

/**
 * Generic output-format/style rules are NOT durable user memories.
 */
function isFormatStyleRule(line: string, uiLang: Lang): boolean {
  const s = String(line ?? "").trim();
  if (!s) return false;

  if (uiLang === "ja") {
    return /箇条書き|見出し|markdown|マークダウン|トーン|口調|敬語|タメ口|ですます|だ・である|文体|改行|句読点|絵文字|emoji/.test(
      s,
    );
  }

  const sl = s.toLowerCase();
  return /bullet|bullets|numbered list|markdown|heading|headings|tone|style|voice|polite|casual|emoji|emojis/.test(
    sl,
  );
}

/**
 * If the line tries to "lock" output format ("always bullets"), skip it.
 */
function isFormatLockingRule(line: string, uiLang: Lang): boolean {
  const s = String(line ?? "").trim();
  if (!s) return false;

  if (uiLang === "ja") {
    return /必ず.{0,16}(箇条書き|見出し|markdown|マークダウン|絵文字)/.test(
      s,
    );
  }

  const sl = s.toLowerCase();
  return /(always|must).{0,24}(bullet|bullets|markdown|heading|headings|emoji)/.test(
    sl,
  );
}

/**
 * Temporary chat operation notes are NOT durable user memories.
 */
function isTemporaryChatOperationLine(line: string, uiLang: Lang): boolean {
  const s = String(line ?? "").trim();
  if (!s) return false;

  if (uiLang === "ja") {
    return /このチャットでは|このスレッドでは|本チャット|引き継ぎ|新規チャット|npm run build|git add|git commit|git push|コマンド|cmd|PowerShell|ターミナル|terminal|エクスプローラー|Dev tool|デブツール|ログ|キャッシュ|再読み込み|F5|ビルドOK|buildOK|gitOK/.test(
      s,
    );
  }

  const sl = s.toLowerCase();
  return /in this chat|in this thread|handoff|carry over|new chat|npm run build|git add|git commit|git push|command|cmd|powershell|terminal|devtools|developer tools|log|cache|reload|f5|build ok|git ok/.test(
    sl,
  );
}

/**
 * Generic self-help / non-user-specific statements are NOT durable user memories.
 */
function isGenericNonUserSpecific(line: string, uiLang: Lang): boolean {
  const s = String(line ?? "").trim();
  if (!s) return true;

  if (uiLang === "ja") {
    if (
      /必要である|大切である|重要である|不可欠である|望ましい|べきである|すべき/.test(
        s,
      )
    )
      return true;

    if (
      /思考の成長|自己反省|批判的思考|創造(性|力)|成長(とは|は)|人生|成功|習慣|モチベーション|目標|ステップ|やるべき|次に何/.test(
        s,
      )
    )
      return true;

    if (/今日は晴れ|天気が良い|今日は(良い|悪い)日|外に出て/.test(s))
      return true;

    return false;
  }

  const sl = s.toLowerCase();

  if (/need to|must|should|it is important|it is necessary/.test(sl))
    return true;

  if (
    /personal growth|success|life|motivation|habit|goals|critical thinking|creativity|thinking growth/.test(
      sl,
    )
  )
    return true;

  if (/weather is nice|today is sunny|go outside/.test(sl)) return true;

  return false;
}

/**
 * System/core/product definitions are NOT USER_MEMORY.
 */
function isSystemOrProductCoreLike(line: string, uiLang: Lang): boolean {
  const s = String(line ?? "").trim();
  if (!s) return true;

  if (uiLang === "ja") {
    return /SYSTEM_CORE|世界向け|憲法|存在定義|回答定義|非機能原則|HOPYは思考のインフラ|思考のインフラ|開発用語|実装都合|MEMORIES仕様|DB最小定義/.test(
      s,
    );
  }

  const sl = s.toLowerCase();
  return /system_core|constitution|world[- ]?ready|core definition|you are hopy|thinking infrastructure|development term|implementation detail|memories spec|db definition/.test(
    sl,
  );
}

/**
 * Temporary feelings / one-off status are NOT durable memories.
 */
function isTransientStateLike(line: string, uiLang: Lang): boolean {
  const s = String(line ?? "").trim();
  if (!s) return true;

  if (uiLang === "ja") {
    return /今日|今|さっき|今回|この瞬間|一時的|少し|ちょっと|疲れた|眠い|つらい|しんどい|落ち込んでいる|不安だ|うれしい|悲しい|むかつく/.test(
      s,
    );
  }

  const sl = s.toLowerCase();
  return /today|right now|just now|this time|temporary|a bit|tired|sleepy|sad|upset|anxious|happy|angry|stressed/.test(
    sl,
  );
}

/**
 * Durable hints
 */
function looksDurableJa(line: string) {
  return /今後|以後|固定|禁止|必ず|使わない|使用しない|表記|不変|絶対|二度と|長期|継続|重視|嫌い|嫌|安心|方針|基本|原則|理想|してほしい|して欲しい|進めてほしい|進めて欲しい/.test(
    line,
  );
}

function looksDurableEn(line: string) {
  return /from now on|going forward|always|never|prefer|must|fixed|do not|don't call me|long-term|ongoing|important to me|i dislike|i hate|i want you to|i feel safer/.test(
    line.toLowerCase(),
  );
}

function importanceJa(line: string): number {
  if (/一番嫌|最も嫌|禁止|使わない|使用しない|必ず|不変|絶対|二度と/.test(line))
    return 5;
  if (/固定|今後|以後|長期|継続|重視|嫌い|嫌|方針|基本|原則/.test(line))
    return 4;
  if (/希望|好み|呼んで|呼称|表記|安心|理想/.test(line)) return 3;
  return 3;
}

function importanceEn(line: string): number {
  const s = line.toLowerCase();
  if (/never|must|do not|don't|absolute|i hate|i dislike/.test(s)) return 5;
  if (
    /fixed|always|going forward|from now on|long-term|ongoing|important to me/.test(
      s,
    )
  )
    return 4;
  if (/prefer|call me|naming|spelling|i feel safer|i want you to/.test(s))
    return 3;
  return 3;
}

function inferMemoryType(line: string, uiLang: Lang): HeuristicMemoryType {
  const s = String(line ?? "").trim();

  if (uiLang === "ja") {
    if (/嫌い|嫌|安心|好み|希望|してほしい|して欲しい|進めてほしい|進めて欲しい/.test(s)) {
      return "trait";
    }

    if (/方針|基本|原則|重視|長期|継続|固定|禁止|必ず|絶対/.test(s)) {
      return "trait";
    }

    return "theme";
  }

  const sl = s.toLowerCase();

  if (/i hate|i dislike|i feel safer|i prefer|i want you to|don't call me/.test(sl)) {
    return "trait";
  }

  if (/policy|principle|always|never|must|going forward|from now on/.test(sl)) {
    return "trait";
  }

  return "theme";
}

function buildHeuristicMemoryItem(params: {
  content: string;
  importance: number;
  memoryType: HeuristicMemoryType;
}): HeuristicMemoryItem {
  return {
    content: params.content,
    importance: params.importance,
    memory_type: params.memoryType,
    source_type: "auto",
    save_hint: "save",
  };
}

function extractFromRaw(params: {
  uiLang: Lang;
  raw: string;
  maxItems: number;
}): HeuristicMemoryItem[] {
  const { uiLang, raw, maxItems } = params;
  const lines = uiLang === "en" ? splitSentencesEn(raw) : splitSentencesJa(raw);

  const out: HeuristicMemoryItem[] = [];

  for (const line of lines) {
    if (out.length >= maxItems) break;

    if (isFormatStyleRule(line, uiLang)) continue;
    if (isFormatLockingRule(line, uiLang)) continue;
    if (isTemporaryChatOperationLine(line, uiLang)) continue;
    if (isSystemOrProductCoreLike(line, uiLang)) continue;
    if (isGenericNonUserSpecific(line, uiLang)) continue;
    if (isTransientStateLike(line, uiLang)) continue;

    if (uiLang === "ja") {
      if (!looksDurableJa(line)) continue;
      const content = trimTo(line, 120);
      if (!content) continue;

      uniqPush(
        out,
        buildHeuristicMemoryItem({
          content,
          importance: importanceJa(line),
          memoryType: inferMemoryType(line, uiLang),
        }),
      );
    } else {
      if (!looksDurableEn(line)) continue;
      const content = trimTo(line, 120);
      if (!content) continue;

      uniqPush(
        out,
        buildHeuristicMemoryItem({
          content,
          importance: importanceEn(line),
          memoryType: inferMemoryType(line, uiLang),
        }),
      );
    }
  }

  return out.slice(0, Math.max(0, Math.min(3, maxItems)));
}

export function extractHeuristicMemories(params: {
  uiLang: Lang;
  userText: string;
  assistantText?: string | null;
  maxItems?: number;
}): MemoryItem[] {
  const { uiLang, userText, maxItems = 2 } = params;

  const normalizedMaxItems = Math.max(0, Math.min(3, maxItems));
  const userRaw = String(userText ?? "").trim();

  if (!userRaw) return [];

  return extractFromRaw({
    uiLang,
    raw: userRaw,
    maxItems: normalizedMaxItems,
  });
}

/*
【このファイルの正式役割】
会話本文から、長期的に残す価値がある記憶候補だけを決定論的なルールで抽出する補助抽出層。
HOPY生成の confirmed memory candidates がある場合は上流の確定候補を優先し、
このファイルではユーザー自身の入力に含まれる継続的な好み・方針・支援条件を conservative に拾う。

【今回このファイルで修正したこと】
- heuristic 由来の記憶候補に memory_type / source_type / save_hint を付け、下流で support_context 扱いにならないようにした。
- ユーザーのHOPY開発支援方針、継続的な好み、嫌なこと、安心条件を trait / theme として候補化できるようにした。
- 一時的なチャット操作や git / build / log などは保存しないまま、差分回答・全文回答・1ファイルずつ進める等の継続的な支援方針は保存候補にできるようにした。
- assistantText からの heuristic 抽出をやめ、HOPY回答本文の一部がユーザーMEMORIESとして混ざる流れを止めた。
- state_changed、state_level、current_phase、Compass、HOPY回答○、Future Chain、Learning、Dashboard、UI、DB schema には触れていない。

/app/api/chat/_lib/memory/heuristic.ts
*/